- name: test my new module
  hosts: localhost
  vars_files: 
    - test_var.yaml

  roles:
    - role: './roles/validator'
      vars:
        schema: 'schema.yaml'

  tasks:
    - name: test
      debug:
        msg: 'test validating variables'