---

- name: Validate Ansible variables using the provided YAML schema
  vars_schema_validator:
    var: '{{ vars }}'
    schema: '{{ schema }}'
  register: validation_result

- name: Display validation result
  debug:
    msg: '{{ validation_result }}'
